### ISSUE TITLE
It should use the new es_extended Weight System...

### ISSUE THREAD

**Issue by YisusOnDev** [LilRez/esx_inventoryhud-weight-based#1]
We don't need to use a custom weight system, it should use the new and latest es_extended weight system.

Thanks

**Comment by VapeJezzy** [comment]
> We don't need to use a custom weight system, it should use the new and latest es_extended weight system.
> 
> Thanks

so ?

**Comment by YisusOnDev** [comment]
> > We don't need to use a custom weight system, it should use the new and latest es_extended weight system.
> > Thanks
> 
> so ?

It should implement the new weight system from esx xd
